config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: "tasks#index", as: :root
  get "tasks/new", to: "tasks#new", as: :new
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to root_path
  end

  private
  def task_params
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
<% @tasks.each do |task| %>
<li><%=link_to "#{task.title}  #{task.completed}", task_path(task) %></li>
<% end %>
</ul>

<%= link_to "+Add a new task", new_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= form_with model: @task do |t| %>
 <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
  <% end %>

<%=link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title%></h1>

<%= @task.details %>
<% if @task.completed == false %>
  <p>this task is not completed yet </p>
  <%else %>
  <p>this task is completed </p>
<% end %>

<%=link_to "Back to list", tasks_path %>